Move Indy NodeJS wrapper codebase here
hyperledger/aries-sdk-javascript pull request #1
Opened 2019-08-21 15:40 UTC by jadhavajay

To start with I am moving the Indy NodeJS wrapper as it is here, with no code changes at all except few Readme changes.

2019-08-22 19:49 UTC, smithbk reviewed
Jadhavajay, I understand that you are just getting started, but I'd like to understand the goal of this SDK before I review.  This is probably better to discuss on a call, but I assume the goal is to implement a higher level agent API.

Since Aries is supposed to allow other implementations other than indy, it would seem reasonable that we at least start by deciding on a directory structure which would allow other implementations to be plugged in.

For example, perhaps something similar to:
```
-- api (The Aries agent API - to be defined)
    -- spi (The service provider API which is used by the Aries agent APIs - i.e. an abstraction of the indy APIs)
        -- indy (the current indy code goes here)
            -- test (indy test code here)
        -- another implementation of the SPI in the future
-- test (test for the higher-level agent APIs)
```

2019-08-28 15:09 UTC, matt-raffel-kiva requested changes
For all js files:  terminate each statement with semicolon.  replace var with const and let in functions.

2019-08-28 15:09 UTC, matt-raffel-kiva commented on src/IndyError.js
> +      if (typeof details.message === 'string') {
var should be replaced with const to avoid potential conflicts in global namespace

2019-08-28 15:09 UTC, matt-raffel-kiva commented on src/IndyError.js
> +var util = require('util')
every line should be terminated with semicolon.  this is an industry standard and is enforced with linters.

2019-08-28 15:09 UTC, matt-raffel-kiva commented on src/IndyError.js
> +    }
we need to do something here.  just eating the exception will make it very difficult to debug when a problem happens.

2019-08-28 15:09 UTC, matt-raffel-kiva commented on src/wrapIndyCallback.js
> +
all lines should be terminated with semicolon.

2019-08-28 15:09 UTC, matt-raffel-kiva commented on src/wrapIndyCallback.js
> +  if (!cb) {
var should be replaced with let

2019-08-28 15:09 UTC, matt-raffel-kiva commented on test/anoncreds.js
> +var test = require('ava')
every statement should be terminated with semicolon

2019-08-28 15:09 UTC, matt-raffel-kiva commented on test/anoncreds.js
> +  var pool = await initTestPool()
local variables need to be declared with const or let.

2019-08-28 15:09 UTC, matt-raffel-kiva commented on test/blob.js
> +var test = require('ava')
please see my comments for the previous files.  same for this one.

2019-08-28 15:09 UTC, matt-raffel-kiva commented on test/cache.js
> +var test = require('ava')
please see my comments for the previous files.  same for this one.

2019-08-28 15:09 UTC, matt-raffel-kiva commented on test/crypto.js
> +var test = require('ava')
please see my comments for the previous files.  same for this one.

2019-08-28 15:09 UTC, matt-raffel-kiva commented on test/did.js
> +var test = require('ava')
please see my comments for the previous files.  same for this one.

2019-08-29 07:48 UTC, jadhavajay commented
Thanks @matt-raffel-kiva for your comments on this PR.
This PR is just a code move from previous Indy Node.js wrapper repository.

We (@smithbk & me) discussed last week to have a Zoom call together and discuss the roadmap of how to take this further with Aries Framework idea in mind. We also discussed about using TypeScript instead of ES.

I will catch up with you on RocketChat and will schedule a Zoom call.

2019-09-09 17:18 UTC, closed without merging

2019-09-11 19:46 UTC, esplinr commented
I was surprised to see this PR closed. I agree with @smithbk that we should define how to be ledger-independent, but I don't think that should prevent taking the existing Indy code as the foundation for an aries-js-wrapper and then iterating. It's hard for interested contributors to know how to collaborate when the repository is completely empty. A simple README.md stating the current state of the project and current efforts would also help a lot.

2019-09-11 19:47 UTC, matt-raffel-kiva commented
I don’t have maintainer rights on that repo.  If I could get that, then I could help out more. 

> On Sep 11, 2019, at 1:46 PM, Richard Esplin <notifications@github.com> wrote:
> 
> I was surprised to see this PR closed. I agree with @smithbk that we should define how to be ledger-independent, but I don't think that should prevent taking the existing Indy code as the foundation for an aries-js-wrapper and then iterating. It's hard for interested contributors to know how to collaborate when the repository is completely empty. A simple README.md stating the current state of the project and current efforts would also help a lot.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2019-09-11 19:47 UTC, ryjones commented
I apologize. I did a force-push to fix a DCO issue, because I didn't see there was a PR in flight. This is my fault.

2019-09-11 19:48 UTC, ryjones commented
@esplinr I can't re-open the PR b/c master changed under it.

2019-09-12 15:26 UTC, esplinr commented
Thanks for the explanation @ryjones . That makes sense. I misinterpreted what was going on based on the comments, but now I see that @smithbk was only prompting a helpful discussion and a decision hadn't yet been made.

@matt-raffel-kiva: I think @jadhavajay can work with @ryjones to grant those rights.